#!/bin/bash
#
DOCROOT=`grep -Po '^chdir = \K.*' /etc/php-fpm.d/www.conf 2>/dev/null`
if [ -z ${DOCROOT} ];then
	DOCROOT="/usr/local/emhttp"
fi

${DOCROOT}/plugins/lcd_manager/scripts/rc.usb_manager USBMgrBuildConnectedStatus
